

language: python

python:
  - "2.7"

# command to install dependencies
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE test_api;" -U postgres

install:
 
  - pip install -r requirements.txt
  - pip install coveralls
env:
  - FLASK_APP="run.py"
  - SECRET="this is andela"
  - APP_SETTINGS="development"
  - DATABASE_URL="postgresql://localhost/rest_api"
# command to run tests

script: 
    
    - nosetests --with-coverage

after_success: coveralls
